baseURL = "https://shallowbrooksoftware.com/"
languageCode = "en-us"
title = "Shallow Brook Software"
theme = "minimal"
pluralizelisttitles = false

[params]
    author = "Andrew Dailey"
    description = "Simple software that babbles loudly"
    githubUsername = "#"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["c", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/theandrew168/"
    name = "github"
    weight = 1
