name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install PurgeCSS
      run: |
        npm install -g purgecss
    - name: Build blog
      run: |
        make blog
    # intentionally absent from the Makefile due to destructive behavior
    # can't use the blog templates since some style comes from blogify.go
    - name: Strip unused CSS
      run: >
        purgecss
        -c scripts/purgecss.config.js
        -con templates/*.tmpl
        -con posts/*.html
        -con posts/**/*.html
        -css static/css/*
        -o static/css/
    - name: Build project
      run: |
        make dist
    - name: Copy build artifacts
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SBS_HOSTNAME }}
        username: ${{ secrets.SBS_SSH_USER }}
        key: ${{ secrets.SBS_SSH_KEY }}
        source: dist/*
        strip_components: 1
        target: /home/${{ secrets.SBS_SSH_USER }}/
    - name: Restart web service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SBS_HOSTNAME }}
        username: ${{ secrets.SBS_SSH_USER }}
        key: ${{ secrets.SBS_SSH_KEY }}
        script: |
          sudo systemctl restart sbs
